name: "[Performance] Lighthouse"
run-name: Lighthouse run ${{github.run_number}}

on: workflow_dispatch
jobs:
  Run_Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.18
      - name: Install Lighthouse
        run: npm i -g lighthouse
      - name: Check Versions
        run: |
          echo "===Node Version===" 
          node --version  
          echo "===Lighthouse Version===" 
          lighthouse --version
      - name: Run Lighthouse on prod
        run: |
          lighthouse --chrome-flags="--headless --no-sandbox" https://briondev.com --output "json,html" --output-path ./lh
      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          name: report
          path: ${{github.workspace}}/lh.report.html